/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SalaHost.java
 *
 * Created on 05/06/2012, 01:59:26
 */

package View;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import ludo.Jogadas;
import ludo.Tabela;

/**
 *
 * @author Felipe
 */
public class SalaHost extends javax.swing.JFrame {

    /** Creates new form SalaHost */
    public SalaHost(int tamanho) {
        initComponents();
        
         this.setResizable(false);//impede que o tamanho da tela seja alterado
        setLocationRelativeTo( null ); // Centraliza Janela
        
        System.out.println("Interface tabela "+Inicial.getNome());
        
           System.out.println("tamanho da tabela"+tamanho); 
        for (int i = 0; i <tamanho ; i++) {
            ((DefaultTableModel) jTable1.getModel()).addRow(Tabela.getTabela()[i]);

        }
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        iniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Players Online", "IP"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        iniciar.setText("Iniciar Partida");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36));
        jLabel1.setText("Ludo - Multiplayer");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 344, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(139, 139, 139)
                .add(iniciar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(29, 29, 29)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(iniciar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        Jogadas jogad = new Jogadas();
                
        Thread jogadthr = new Thread(jogad);
        jogadthr.start();
        
        
        
        JFrame frame = new JFrame("Ludo Multiplayer");
        frame.add(new JanelaTabuleiro());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        
        jogad.setJanela(frame.add(new JanelaTabuleiro()));
        this.dispose();
    }//GEN-LAST:event_iniciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
