/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SalaGuest.java
 *
 * Created on 05/06/2012, 01:56:47
 */
package View;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import ludo.Jogadas;
import ludo.Tabela;

/**
 *
 * @author Felipe
 */
public final class SalaGuest extends javax.swing.JFrame {

    /** Creates new form SalaGuest */
    public SalaGuest(int tamanho) {
        initComponents();
        
         this.setResizable(false);//impede que o tamanho da tela seja alterado
        setLocationRelativeTo( null ); // Centraliza Janela
        
        
        
        
        for (int i = 0; i <tamanho ; i++) {
            ((DefaultTableModel) jTable1.getModel()).addRow(Tabela.getTabela()[i]);
            

        }
        
        //tentativa de abrir a janelaTabuleiro
        
           
        esperarInicioPartida();
    }
    
    public void esperarInicioPartida(){
    Jogadas jogad = new Jogadas();
                
        Thread jogadthr = new Thread(jogad);
        jogadthr.start();
   
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36));
        jLabel1.setText("Ludo - Multiplayer");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Players Online", "IP"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
